import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
// import { Browser } from "react-window-ui";
import { Browser, MacTerminal } from "react-window-ui";
import Typewriter from "typewriter-effect";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main className={styles.main}>
        <div className={styles.headerContainer}>
          <h1 className={styles.title}>
            NEXTjs Optimization with <span>Vantage</span>.
          </h1>
          <motion.div
            initial={{ x: 500 }}
            animate={{ x: 0 }}
            transition={{ ease: "easeOut", duration: 0.3 }}
            // transition={{ type: "spring", stiffness: 200, damping: 20 }}
          >
            <Image
              width={1006}
              height={601}
              layout='intrinsic'
              className={styles.screenshot1}
              src='/screenshot1.png'
              alt='Screenshot of Vantage'
            />
          </motion.div>
        </div>
        <div className={styles.headerContainer}>
          <Browser background='lightgray' className={styles.terminalContainer}>
            <pre>
              <code>
                <Typewriter
                  options={{
                    strings: ["npx vantage"],
                    autoStart: true,
                    loop: true,
                  }}
                />
              </code>
            </pre>
          </Browser>
          <div>Text</div>
        </div>
      </main>
    </div>
  );
};

export default Home;
