import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
// import { Browser } from "react-window-ui";
import { Browser, MacTerminal } from "react-window-ui";
import Typewriter from "typewriter-effect";
import CardContainer from "./Containers/CardContainer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vantage</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main className={styles.main}>
        <div className={styles.headerContainer}>
          <motion.h1
            className={styles.title}
            initial={{ x: -600 }}
            animate={{ x: 0 }}
          >
            NEXTjs Optimization with <span>Vantage</span>.
          </motion.h1>
          <motion.div
            initial={{ x: 600 }}
            animate={{ x: 0 }}
            // transition={{ ease: "easeOut", duration: 0.3 }}
            // transition={{ type: "spring", stiffness: 200, damping: 20 }}
          >
            <Image
              width={1006}
              height={601}
              layout='intrinsic'
              className={styles.screenshot1}
              src='/screenshot1.png'
              alt='Screenshot of Vantage'
            />
          </motion.div>
        </div>
        <div className={styles.headerContainer}>
          <Browser background='lightgray' className={styles.terminalContainer}>
            <pre>
              <code>
                <Typewriter
                  options={{
                    strings: ["npm install vantage-next --save-dev"],
                    autoStart: true,
                    loop: true,
                  }}
                />
              </code>
            </pre>
          </Browser>
          <div>
            Easily install with npm and instantly start monitoring web vitals
            with each new commit
          </div>
        </div>
        <div className={styles.cardContainer}>
          <span>Meet the team!</span>
          <CardContainer />
        </div>
      </main>
    </div>
  );
};

export default Home;
